name = "AdventOfCode"
uuid = "7ef4cfdd-3fec-4d8b-b242-bcc5161d01d5"
authors = ["Sebastian Rollen <seb@rollen.io>"]
version = "1.3.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
HTTP = "1"
JSON = "0.21"
Mocking = "0.7, 0.8"
TimeZones = "1.19.0"
julia = "1.6"
