name = "AdventOfCode"
uuid = "7ef4cfdd-3fec-4d8b-b242-bcc5161d01d5"
authors = ["Sebastian Rollen <sebastian.rollen@betterment.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
